[package]
name = "api-test"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { version = '1.0', features = ["full"] }
axum = "0.8"
serde = { version = "1.0", features = ["derive"] }
ed25519-dalek = "2.1"
hex = "0.4"
dotenv = "0.15"
